Algoritmo "funçoes matematicas"

Var
    x, y, z ,a, b, c, d : real


Inicio
          x <- 2
          y <- 3
          z <- -7
          
          a <- Exp(x,y) // expoente
          b <- raizQ(y) // raiz quadrada
          c <- PI   //numero PI = 3,14...
          d <- Abs(z) //numero sem o sinal
          
          escreval(a)
          escreval(b)
          escreval(c)
          escreval(d)

Fimalgoritmo